# Generated by Django 5.1.4 on 2025-01-07 21:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo', models.CharField(choices=[('D1', 'Direita 1'), ('E1', 'Esquerda 1')], default='D1', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localizacao')),
            ],
        ),
        migrations.CreateModel(
            name='Contagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_pessoas', models.PositiveIntegerField()),
                ('visitantes', models.PositiveIntegerField()),
                ('criancas', models.PositiveIntegerField()),
                ('conversoes', models.PositiveIntegerField(default=0)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('validado', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.host')),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reuniao')),
            ],
        ),
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('contagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.contagem')),
            ],
        ),
    ]
