# Generated by Django 5.1.4 on 2025-01-13 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Localização',
                'verbose_name_plural': 'Localizações',
            },
        ),
        migrations.CreateModel(
            name='Reuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localizacao')),
            ],
            options={
                'verbose_name': 'Reunião',
                'verbose_name_plural': 'Reuniões',
            },
        ),
        migrations.CreateModel(
            name='Contagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reuniao', models.DateField(auto_now_add=True)),
                ('host_nome', models.CharField(max_length=100)),
                ('total_pessoas', models.PositiveIntegerField(default=0)),
                ('visitantes', models.PositiveIntegerField(default=0)),
                ('criancas', models.PositiveIntegerField(default=0)),
                ('conversoes', models.PositiveIntegerField(default=0)),
                ('voluntarios', models.PositiveIntegerField(default=0)),
                ('data_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('validado', models.BooleanField(default=False)),
                ('reuniao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reuniao')),
            ],
            options={
                'verbose_name': 'Contagem',
                'verbose_name_plural': 'Contagens',
            },
        ),
        migrations.CreateModel(
            name='Validacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('contagem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.contagem')),
            ],
            options={
                'verbose_name': 'Validacao',
                'verbose_name_plural': 'Validacões',
            },
        ),
    ]
