# Generated by Django 5.1.4 on 2025-01-07 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_contagem_host_contagem_host_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contagem',
            options={'verbose_name': 'Contagem', 'verbose_name_plural': 'Contagens'},
        ),
        migrations.AlterModelOptions(
            name='localizacao',
            options={'verbose_name': 'Localização', 'verbose_name_plural': 'Localizações'},
        ),
        migrations.AlterModelOptions(
            name='reuniao',
            options={'verbose_name': 'Reunião', 'verbose_name_plural': 'Reuniões'},
        ),
        migrations.AlterModelOptions(
            name='validacao',
            options={'verbose_name': 'Validacao', 'verbose_name_plural': 'Validacões'},
        ),
        migrations.AlterField(
            model_name='contagem',
            name='criancas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contagem',
            name='total_pessoas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contagem',
            name='visitantes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
