# Generated by Django 5.1.4 on 2025-01-08 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_contagem_options_alter_localizacao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='data',
        ),
        migrations.AddField(
            model_name='contagem',
            name='data_reuniao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
