# Generated by Django 5.1.4 on 2025-01-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_reuniao_data_contagem_data_reuniao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contagem',
            name='data_reuniao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
